### PR TITLE
update ompl dep

### PR DESCRIPTION
**Pull request by acxz**

### CODE REVIEW

**Comment by jwhendy** [comment]
I can't get this to work at the moment. I think it *should* work, but ~I can't get `ompl` to build~ (see edit below). My process:
- remove `ros-melodic-ompl` (removes all the rest of ros-melodic-moveit-*`)
- apply these changes to `ros-melodic-moveit-planners-ompl`
- edit the `ros-melodic-ompl` `PKGBUILD` to the essentially just make it `ompl`, which was required because AUR's `ompl` [doesn't build](https://aur.archlinux.org/packages/ompl/#pinned-715280).
- despite building `ros-melodic-ompl` within a week, I can no longer get it to build and the error is unclear.

**Edit:** so, it turns out if I just keep retrying the build, eventually the modified `ompl` just works. No idea. Now I can't get `ros-melodic-moveit-planners-ompl` to rebuild using the updated `PKGBUILD`. Let me know your thoughts.

```
[ 52%] Building CXX object ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/state_validity_checker.cpp.o
In file included from /usr/include/boost/throw_exception.hpp:36,
                 from /usr/include/boost/math/policies/error_handling.hpp:23,
                 from /usr/include/boost/math/special_functions/round.hpp:14,
                 from /opt/ros/melodic/include/ros/time.h:58,
                 from /opt/ros/melodic/include/ros/ros.h:38,
                 from /opt/ros/melodic/include/urdf/model.h:50,
                 from /opt/ros/melodic/include/moveit/robot_model/robot_model.h:43,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space.h:41,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h:40,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h:40,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/constraints_library.h:41,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/src/constraints_library.cpp:37:
/usr/include/boost/exception/exception.hpp:461:13: internal compiler error: Segmentation fault
  461 |             rethrow() const
      |             ^~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
```

Modified `ros-melodic-ompl` -> `ompl` `PKGBUILD`
```
# Script generated with import_catkin_packages.py
# For more information: https://github.com/bchretien/arch-ros-stacks
# Maintainer: Fan Jiang <i@fanjiang.me>
# Contributor: Sean Greenslade <aur@seangreenslade.com>
pkgdesc="ROS - OMPL is a free sampling-based motion planning library."
url='https://ompl.kavrakilab.org'

pkgname='ompl'
pkgver='1.4.1'
arch=('any')
pkgrel=2
license=('BSD')

makedepends=('cmake'
  'ros-build-tools'
  boost
  eigen)

depends=(
  boost
  eigen)

_dir="ompl-${pkgver}"
source=("${pkgname}-${pkgver}.tar.gz"::"https://github.com/ompl/ompl/archive/${pkgver}.tar.gz"
	"boost-fix.patch")
sha256sums=('ad3e8e2201772de5e689ba1eee2d845bea1c7f3cdf08de6d282583fbe699856c'
 	    '41a66f47adc11165278f27c2c565e7e0b37d406c45794383ab8fe1ed6a13cadc')

prepare() {
  cd ${srcdir}/${_dir}
  patch -uN demos/PlannerData.cpp ../../boost-fix.patch || return 1
}

build() {

  # Create build directory
  [ -d ${srcdir}/build ] || mkdir ${srcdir}/build
  cd ${srcdir}/build

  # Fix Python2/Python3 conflicts
  /usr/share/ros-build-tools/fix-python-scripts.sh -v 3 ${srcdir}/${_dir}

  # Build project
  cmake ${srcdir}/${_dir} \
        -DCMAKE_BUILD_TYPE=Release \
        -DCATKIN_BUILD_BINARY_PACKAGE=ON \
        -DCMAKE_INSTALL_PREFIX=/opt/ros/melodic \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DSETUPTOOLS_DEB_LAYOUT=OFF
  make
}

package() {
  cd "${srcdir}/build"
  make DESTDIR="${pkgdir}/" install
}
```

**Comment by acxz** [comment]
I think we wait this storm out, until `ompl` can be compiled and built successfully. I am not using `ompl` rn so it is not that pressing for me, but if I do before and new ompl version is released then I will just patch `omplapp` and request the `ompl` maintainer to do the same.

**Comment by acxz** [comment]
But at the very least this PKGBUILD should work, since `ros-melodic-ompl` is not maintained upstream anymore. I think the merge should happen, but I understand being able to successfully build before merging.

**Comment by jwhendy** [comment]
In theory, I completely agree. In practice, I'm super confused. I can build `ompl` (if I just make, let it fail, then retry where it left off ~3x) which is identical to `ros-melodic-ompl`. I just don't understand why when I switch out the deps, I can't build `ros-melodic-moveit-planners-ompl` anymore.

```
[ 56%] Building CXX object ompl_interface/CMakeFiles/moveit_ompl_interface.dir/src/detail/projection_evaluators.cpp.o
In file included from /usr/include/c++/9.2.0/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
                 from /usr/include/c++/9.2.0/bits/allocator.h:46,
                 from /usr/include/c++/9.2.0/string:41,
                 from /usr/include/c++/9.2.0/bits/locale_classes.h:40,
                 from /usr/include/c++/9.2.0/bits/ios_base.h:41,
                 from /usr/include/c++/9.2.0/ios:42,
                 from /usr/include/c++/9.2.0/ostream:38,
                 from /usr/include/c++/9.2.0/iterator:64,
                 from /usr/include/boost/concept_check.hpp:22,
                 from /opt/ros/melodic/include/ompl/base/State.h:40,
                 from /opt/ros/melodic/include/ompl/base/StateSpace.h:40,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/parameterization/model_based_state_space.h:40,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/model_based_planning_context.h:40,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/include/moveit/ompl_interface/planning_context_manager.h:40,
                 from /home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/src/planning_context_manager.cpp:37:
/usr/include/c++/9.2.0/ext/new_allocator.h: In constructor ‘__gnu_cxx::new_allocator<_Tp>::new_allocator() [with _Tp = moveit_msgs::OrientationConstraint_<std::allocator<void> >]’:
/usr/include/c++/9.2.0/ext/new_allocator.h:80:47: internal compiler error: Segmentation fault
   80 |       new_allocator() _GLIBCXX_USE_NOEXCEPT { }
      |                                               ^
Please submit a full bug report,
with preprocessed source if appropriate.
```

**Comment by jwhendy** [comment]
Bizarre. If I keep trying to make again, it faults out in a different place every time.

```
### try 1
/usr/include/boost/math/policies/policy.hpp:683:1: internal compiler error: Segmentation fault
  683 | }

### try 2
/home/jwhendy/installed/build/ros-melodic-aur/ros-melodic-moveit-planners-ompl/src/moveit-1.0.2/moveit_planners/ompl/ompl_interface/src/constraints_library.cpp:614:1: internal compiler error: Segmentation fault
  614 | }

### try 3
/usr/include/c++/9.2.0/bits/stl_construct.h:138:5: internal compiler error: Segmentation fault
  138 |     }
```

**Comment by acxz** [comment]
I know this might be controversial but since both `ompl` and `ros-melodic-ompl` fail to build (consistently) and `ompl` is the actual dependency not `ros-melodic-ompl`, I am going to merge this in. #2 will still remain open.

**Comment by bionade24** [comment]
I think we can simply stop packaging ompl ourselves and use this package. Why should it be controversial?

**Comment by jwhendy** [comment]
I had a `btrfs` failure resulting in a reinstall last weekend. I will say that this really hung me up but it might be because I was using `aurutils` pointed at AUR vs. my previous setup of building all from the repos here. I agree it's not controversial, as if you look at the sources `ompl` == `ros-melodic-ompl`.

I think this is the only package that actually depends on `ros-melodic-ompl`, but `aur sync` still kept trying to bring it in for `ros-melodic-moveit` and `ros-melodic-moveit-planners`. Hopefully it's just because on AUR `ros-melodic-moveit` -> `ros-melodic-moveit-planners` -> `ros-melodic-moveit-planners-ompl` -> `ros-melodic-ompl`.

I'm guessing this is not sync'd as this PR was merged 23 days ago but AUR still failed me just a few days ago.

**Comment by bionade24** [comment]
I saw it, so I'll fix it. The packae doesn't build because it can't find `ompl` als build dep. 
But just curious: Why have you got an btrfs failure?  For me, this was only some legend that doesn't happen under normal circumstances.

**Comment by bionade24** [comment]
Does `ompl` fail for you, too?

**Comment by bionade24** [comment]
Ok, I saw the comments. I'll simply push it and don't wait for the build.

**Comment by jwhendy** [comment]
`ompl` worked for me. I got it installed over the weekend. I did just check via `git diff` and it looks like I bumped to 1.4.2 while I was messing with things. As in, I cloned this repo, changed the pkgname to `ompl`, bumped the version, and built.

---

No idea on `btrfs`. Suddenly chromium would quit and I couldn't open it back up, complaining about a `SingletonLock` file. I'd went to delete that (thinking it got confused that it was still running) and found out my whole root was mounted `ro`. I rebooted and all was fine. Then it happened again. After maybe four of these instances, I booted into an arch install usb and started looking at `btrfs check`, finding a bunch of not great looking stuff.

My takeaway:
- things were probably fine. I could still mount, and I did a final backup just fine
- the errors were minimal compared to others (like some expected number of writes was off by one vs. similar errors online being off by hundreds)
- btrfs support and documentation is garbage. I was so insanely frustrated that googling various forms of my errors never led to a conclusive answer on how to resolve. Not only this, but their own mailing list is filled with dead ends, unanswered emails, etc. I tried to post on irc and no mod was present to let me in. Linux bug reports get closed because no one does anything and then it's time for the next release. Maybe it has so few issues so these bugs are rare, non-reproducible and thus finding a solution is hard? Dunno, but since it was Friday and things were not looking good, I decided to just declare bankruptcy and re-install. With good backups, I was 80% back to golden by 3a on Saturday :) 

[Link](https://www.reddit.com/r/btrfs/comments/ejqhyq/any_hope_of_recovering_from_various_errors_root/) to some of the errors if you want to see what they looked like.

**Comment by bionade24** [comment]
I ment the standalone `ompl` package, we now switch to it. I'll delete `ros-melodic-ompl`.

Did you often run `btrfs scrub` and `fstrim` ? I doing it ~weekly and always fear it could break, but maybe this even saved me. It seems like running `btrfs check` on a mounted disk always produces errors. How many snapshots and subvolumes do you have? I have 6 subvols and 10 who are read-only as snapshots. How good were you're SMART stats? Maybe simply some parts of your (probably SSD?) gave up, and btrfs referened to broken inodes? I'm not sure about that, as I don't know what you ran to polish your filesystem.

**Comment by jwhendy** [comment]
Yes, we're on the same page. `ros-melodic-ompl` *is* `ompl`. The sources are identical.

---

>Did you often run btrfs scrub and fstrim ?

I have `rootflags=compress=lzo,discard,ssd...` which [I understood](https://wiki.archlinux.org/index.php/Solid_state_drive#Continuous_TRIM) was as good as `fstrim`. Hmmm. While looking for something for the below, I found [this](https://btrfs.wiki.kernel.org/index.php/FAQ#Does_Btrfs_support_TRIM.2Fdiscard.3F):

>"-o discard" can have some negative consequences on performance on some SSDs or at least whether it adds worthwhile performance is up for debate depending on who you ask, and makes undeletion/recovery near impossible while being a security problem if you use dm-crypt underneath.

Perhaps I'll switch to `fstrim` afterall.

I did not run `btrfs scrub`, so that could have been a problem, and I plan to do that from now on. I can't refind the command, but I ran whatever tells you if there were io errors and had zero.

Also, `smartctl -t long /dev/foo` passed fine. Dunno.

**Pull request merged**
